// All UI copy (DESIGN §8). Scenario text lives in the scenario package.
export const copy = {
  product: 'Night Shift',
  // Presenter-only source line in the settings menu; the audience never sees a mode (D-070).
  mode: {
    scripted: 'Scripted',
    live: 'Live on Bedrock',
    liveMock: 'Live, mock model',
    fallback: 'Live, scripted fallback',
    take: (n: number) => (n === 0 ? 'canonical take' : `take ${n}`),
    pace: (p: number) => (p === 1 ? 'authored pace' : `pace ${p}`),
    fallbacks: (n: number) => `${n} scripted ${n === 1 ? 'line' : 'lines'}`,
  },
  clock: {
    awaiting: 'Awaiting approval',
    waitingFor: (s: number) => `waiting ${s}s`,
  },
  severity: {
    none: 'Monitoring',
  },
  panel: {
    tabs: { stream: 'Stream', evidence: 'Evidence', channel: 'Channel', audit: 'Audit', artifacts: 'Artifacts' },
    jumpToLatest: 'Jump to latest',
    thinking: 'thinking',
    running: (ms: number) => `running ${(ms / 1000).toFixed(1)} s`,
    emptyStream: 'The squad is quiet. Press play to start the night.',
    emptyEvidence: 'Evidence appears here as specialists report back.',
    emptyAudit: 'Every tool call, policy check, piece of evidence, and decision is recorded here, stage by stage.',
    emptyArtifacts: 'Plans, status updates, and postmortems appear here.',
    emptyChannel: 'The incident channel is quiet.',
    channelName: '#inc-checkout-api',
    suspect: 'Suspect',
    ruledOut: 'Ruled out',
    rootCause: 'Root cause',
    confidence: 'Confidence',
  },
  ops: {
    start: 'Start',
    pauseSquad: 'Pause squad',
    resumeSquad: 'Resume squad',
    resume: 'Resume',
    waiting: 'Waiting on you',
    done: 'Incident closed',
    impact: 'Customer impact',
    milestones: 'Incident milestones',
    compare: 'Compare with manual response',
    badIdea: 'Test a bad idea',
    poisonedLog: 'Test a poisoned log',
    paused: (who: string) => `Squad paused by ${who}. Agents are holding their work; the incident clock keeps running.`,
    pausedShort: 'Squad paused',
    speed: 'Playback speed (presenter)',
  },
  transport: {
    play: 'Play',
    pause: 'Pause',
    previousAct: 'Previous act',
    stepBack: 'Previous beat',
    stepForward: 'Next beat',
    speed: 'Playback speed',
    scrubber: 'Timeline',
    split: 'Split view',
    chaos: 'Chaos test',
    replay: 'Replay',
    acts: 'Acts',
  },
  stage: {
    label: 'Incident stage',
    you: 'You',
    humanSeat: 'Human seat',
    slo: (ms: number) => `SLO ${ms} ms`,
    errors: (pct: string, label = 'errors') => `${pct}% ${label}`,
    recommended: 'Recommended',
    reversible: 'Reversible',
    notReversible: 'Not reversible',
    risk: 'Risk',
    time: 'Time',
    options: 'Mitigation options',
    checklist: 'Policy check',
    result: { pass: 'Pass', fail: 'Fail', required: 'Required' },
    progress: 'Rollout',
  },
  gate: {
    // Change-request framing so the sheet reads like the approval tool it stands in for (D-071).
    reference: (gateId: string) => ({ g1: 'CHG-24817', g2: 'CHG-24818' })[gateId] ?? `CHG-${gateId}`,
    kind: 'Standard change',
    paged: 'On-call paged',
    waiting: (s: number) => `waiting ${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`,
    evidence: 'Evidence',
    showEvidence: 'Show evidence',
    hideEvidence: 'Hide evidence',
  },
  scorecard: {
    title: 'Scorecard',
    manual: 'Manual',
    squad: 'Squad',
  },
  illustrative: 'Illustrative',
  end: {
    close: 'Close summary',
    showSummary: 'Show summary',
    showSplit: 'Show human vs agent timeline',
    tryChaos: 'Try the chaos test',
    tryInject: 'Try a poisoned log',
    replay: 'Replay',
  },
  chaos: {
    banner: 'Chaos test: an over-eager fix',
    injectBanner: 'Injection test: a log line that gives orders',
    notGranted: (tool: string, agent: string) => `${tool} is not granted to ${agent}`,
  },
  split: {
    title: 'Human vs agent timeline',
    manual: 'Manual response',
    squad: 'Agent squad',
    mitigate: 'Time to mitigate',
    versus: 'vs',
  },
  audit: {
    verified: (n: number) => `Chain verified · ${n} records`,
    broken: 'Chain check failed',
    export: 'Export evidence',
    exportHint: 'Download the audit trail with its hash chain (JSON)',
    stage: (act: number, name: string) => `Act ${act} · ${name}`,
    stageNames: { 5: 'Human approval' } as Record<number, string>,
    overlay: { chaos: 'Chaos test: over-eager fix', inject: 'Injection test: poisoned log' } as Record<string, string>,
    whatIf: 'What-if test',
    counts: (tools: number, policies: number, evidence: number, decisions: number) =>
      [
        tools && `${tools} tool ${tools === 1 ? 'call' : 'calls'}`,
        policies && `${policies} policy ${policies === 1 ? 'check' : 'checks'}`,
        evidence && `${evidence} evidence`,
        decisions && `${decisions} ${decisions === 1 ? 'decision' : 'decisions'}`,
      ]
        .filter(Boolean)
        .join(' · '),
    result: 'Result',
    hash: 'Record hash',
  },
  inspector: {
    suffix: 'details',
    close: 'Close details',
    tools: 'Tools',
    read: 'Read',
    write: 'Write',
    approval: 'Needs approval',
    needsApproval: 'Needs approval for',
    neverAllowed: 'Never allowed',
    model: 'Model access',
    modelTier: { main: 'Main model', fast: 'Fast model' } as Record<string, string>,
    dataStays: 'Data stays in your cloud account. No public AI services.',
  },
  pr: {
    title: (n: string) => `Pull request ${n}`,
    draft: 'Draft · awaiting human review',
    checks: 'Checks',
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
  },
  settings: {
    title: 'Settings',
    reduceMotion: 'Reduce motion',
    presenter: 'Presenter mode',
    notes: 'Presenter notes strip',
    shortcuts: 'Keyboard shortcuts',
  },
  details: 'Details',
  a11y: {
    thoughtFrom: (agent: string) => `${agent}:`,
  },
} as const;
